# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Fabian Kostadinov
#tagline:          None
url:              http://fabian-kostadinov.github.io
paginate:         5
baseurl:          /
author:
  name:           Fabian Kostadinov
  url:            http://fabian-kostadinov.github.io
  email:          none@none.com
  
excerpt_separator: <!--more-->

exclude:          [_ignore]

# Don't forget to add these to sitemap.xml
pages_list:
  ABOUT:          '/about'
  ARCHIVE:        '/archive'
  FEED:           '/atom.xml'
  
# Custom vars
version:          1.0.0
github:           
  repo:           https://github.com/fabian-kostadinov
  
comments:
  provider:       disqus
  disqus:
    short_name:   fabian-kostadinov

timezone:         Europe/Zurich